version: '3.8'

services:
  # ProCoder 项目
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3050:80"
    restart: unless-stopped


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5050:8080"
    restart: unless-stopped
    volumes:
      - ./backend/MyDatabase.sqlite:/App/MyDatabase.sqlite
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
